### ISSUE TITLE
Improve sed parser (do not activate with images links)

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/sedy#17]
If an image url contain the sed pattern (e.g. **`s/images/lost/`** in `https://perdu.com/os/images/lost/image.jpg`) the fixer is fired.

This is not the expected behavior.

**Comment by fzaninotto** [comment]
![image](https://cloud.githubusercontent.com/assets/99944/18280152/63c3b654-7458-11e6-9834-83f872fbfbb7.png)

**Comment by Kmaschta** [comment]
Fixed by #52
