### ISSUE TITLE
Make it compatible with the new Github review system

### ISSUE THREAD

**Issue by alexisjanvier** [marmelab/sedy#38]
When sedly is used in a "single review" publication, only the first comment is taken into account (the others return an error, as I foolishly deleted, sorry ...).

**Comment by alexisjanvier** [comment]
I found it : 
```
⚠️ @alexisjanvier, an error occured.
Be sure to check all my commits!
```

**Comment by Kmaschta** [comment]
The error doesn't give much informations. Do you have the webhook payload?
You can find it on your repository > Settings > Webhooks > https://sedy.marmelab.com on the bottom of the page (at the hour of the comment).

**Comment by Kmaschta** [comment]
We're locked by the GitHub's roadmap: https://developer.github.com/changes/2016-10-11-pull-request-review-webhooks/

**Comment by Kmaschta** [comment]
The PR #55 fixed the issue.

Now it barely works because of #59.
But I can close this one!
