### ISSUE TITLE
Sedy failed to detect a change

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/sedy#88]
I registered the Sedy GitHub app on fzaninotto/Faker, commented on a PR with the sedy syntax and... nothing happened.

https://github.com/fzaninotto/Faker/pull/1386#pullrequestreview-84259779

**Comment by Kmaschta** [comment]
It now seems to work:
![image](https://user-images.githubusercontent.com/1819833/38134008-b550262c-3411-11e8-9542-6f08cf5adc52.png)

Feel free to re-open if you have more details.
