### ISSUE TITLE
Edge case with quotes and/or stars?

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/sedy#90]
Sedy didn't work when trying to make the following change:

```
s/ Daemon"/ Daemon*/
```

**Comment by Kmaschta** [comment]
It seems to work on the tests (#92) and on prod:

![image](https://user-images.githubusercontent.com/1819833/38133725-c01f8b16-3410-11e8-90dc-f03554b12117.png)

Feel free to re-open with more details.
